overrides:
  esbuild: 'catalog:'
catalog:
  '@antfu/eslint-config': 4.12.0
  '@libsql/client': 0.15.7
  '@libsql/core': 0.15.7
  '@parcel/watcher': 2.5.1
  '@tailwindcss/vite': 4.1.3
  '@types/node': 22.14.0
  dotenv: 16.5.0
  drizzle-kit: 0.31.1
  drizzle-orm: 0.43.1
  drizzle-valibot: 0.4.2
  esbuild: 0.25.4
  eslint: 9.24.0
  eslint-plugin-format: 1.0.1
  eslint-plugin-vuejs-accessibility: 2.4.1
  jiti: 2.4.2
  nitropack: 2.11.8
  npm-run-all2: 7.0.2
  nuxt: 3.17.4
  reka-ui: 2.2.0
  tailwind-variants: 1.0.0
  tailwindcss: 4.1.3
  typescript: 5.8.3
  valibot: 1.1.0
  vite: 6.3.5
  vue: 3.5.13
  vue-router: 4.5.0
  vue-tsc: 2.2.10
  wrangler: 4.12.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
  - workerd
