catalog:
  '@antfu/eslint-config': 4.12.0
  '@parcel/watcher': 2.5.1
  '@tailwindcss/vite': 4.1.3
  '@types/node': 22.14.0
  eslint: 9.24.0
  eslint-config-prettier: 10.1.2
  eslint-plugin-vuejs-accessibility: 2.4.1
  jiti: 2.4.2
  nitropack: 2.11.8
  npm-run-all2: 7.0.2
  nuxt: 3.16.2
  prettier: 3.5.3
  reka-ui: 2.2.0
  tailwind-variants: 1.0.0
  tailwindcss: 4.1.3
  typescript: 5.8.3
  vite: 6.2.6
  vue: 3.5.13
  vue-router: 4.5.0
  vue-tsc: 2.2.8

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - vue-demi
