catalog:
  '@antfu/eslint-config': 4.12.0
  '@parcel/watcher': 2.5.6
  '@tailwindcss/vite': 4.1.18
  '@types/node': 22.14.0
  eslint: 10.0.2
  eslint-plugin-format: 2.0.1
  eslint-plugin-vuejs-accessibility: 2.5.0
  jiti: 2.4.2
  nitropack: 2.13.1
  npm-run-all2: 7.0.2
  nuxt: 3.17.4
  reka-ui: 2.2.0
  tailwind-variants: 1.0.0
  tailwindcss: 4.1.18
  typescript: 5.8.3
  vite: 6.3.5
  vue: 3.5.29
  vue-router: 4.5.0
  vue-tsc: 2.2.12
  wrangler: 4.12.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
  - workerd
