name: License compliance check

on:
  pull_request:
    branches:
      - main

jobs:
  dependencies:
    name: Dependencies check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Dependency review
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: true
          deny-licenses: 'Apache-1.0, Apache-1.1, GPL-3.0, LGPL-3.0, AGPL-3.0'
