on:
  pull_request_review:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/.git*'
      - '**/*ignore'
      - '**/*rc.json'
    types:
      - submitted

jobs:
  preview-deploy:
    if: github.event.review.state == 'approved'
    name: Deploy (preview)
    environment: pr-preview
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install PNPM
        uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: .node-version
      - id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          gitHubToken: ${{ github.token }}
          apiToken: ${{ secrets.CLOUDFLARE_WORKER_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_WORKER_ACCOUNT_ID }}
          packageManager: pnpm
          command:
            'pages deploy --project-name=pawqar --commit-hash=${{ github.sha }} --branch=pr-${{ github.event.number }}'
          preCommands: |
            pnpm install --frozen-lockfile
            pnpm build:preview
      - name: Comment deployment URL
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Preview URL: ${{ steps.deploy.outputs.pages-deployment-alias-url }} 🚀
